apiVersion: apps/v1
kind: Deployment
metadata:
  name: trump-clock
  labels:
    app: trump-clock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trump-clock
  template:
    metadata:
      labels:
        app: trump-clock
    spec:
      containers:
      - name: trump-clock
        image: trump-clock:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.2"
            memory: "128Mi"
          requests:
            cpu: "0.1"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: trump-clock-service
spec:
  selector:
    app: trump-clock
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trump-clock-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trump-clock-service
            port:
              number: 80

